### ISSUE TITLE
queries

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#1]
Vc deveria usar

https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html#prepared-queries

E nunca o string format de Python.

**Comment by fredsonaguiar** [comment]
Obrigado pela sugestão. A biblioteca permite prefixar um namespaçe, e essa informação é usada por padrão quando não espcificamos namespaçes através de prepared queries. Isto é, a solução atual é similar mas os namespaçes são globalmente especificados.

https://github.com/FredsoNerd/py-ownpt/blob/18771d2ccdcef45db0192abe84eb0ee0272a0d17/pyownpt/ownpt.py#L21
