### ISSUE TITLE
query

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#2]
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L152-L161

A forma mais eficiente é:

```
SELECT ?s ?p ?o 
WHERE
{ 
  VALUES ?p { rdfs:label wn30:lexicalForm wn30:gloss wn30:example }
  ?s ?p ?o . 
  FILTER ( lang(?o) != 'pt') 
}
``` 

E note que neste caso a query não tem parâmetros, apenas os namespaces devem ser passados para que o sistema interprete os prefixos `wn30` e `rdfs`. Para isso existe o parâmetro initNs, veja em https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html#prepared-queries

**Comment by fredsonaguiar** [comment]
Concordo. Corrigido.
