### ISSUE TITLE
words have lexicalform

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#3]
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L65-L66

Novamente, usando `prepared queries` e passando o namespace, a query fica:

```sparql
SELECT ?w 
WHERE
{
 { ?w wn30:lexicalForm ?l . } 
 UNION 
 { ?w a wn30:Word . } 
 FILTER NOT EXISTS { ?s ?p ?w . }
}
```

Mas se antes vc conferir se toda wn30:Word tem wn30:lexicalForm e se tudo que tem wn30:lexicalForm é wn30:Word, sua query fica mais simples. O RDF atual me dá no result para:

```sparql 
SELECT ?w 
WHERE
{
 ?w wn30:lexicalForm ?l . 
 minus 
   { ?w a wn30:Word . }
}
```

E para o inverso:

```sparql
SELECT ?w 
WHERE
{
 ?w a wn30:Word .
 minus 
   { ?w wn30:lexicalForm ?l .  }
}
```

**Comment by arademaker** [comment]
Uma forma alternativa da query que então ficaria simplificada é:

```sparql
SELECT ?w 
WHERE
{
 ?w a wn30:Word . 
 minus 
 { ?s ?p ?w . }
}
```

note o uso do minus vs filter. No AllegroGraph performance não ficou muito diferente.

**Comment by fredsonaguiar** [comment]
Faz sentido, mas não acredito que seja necessário, ou mesmo valha a pena: o custo de substituir uma query por três, apenas por uma query mais curta. O que acha?

**Comment by fredsonaguiar** [comment]
Sobre performance, houve uma queda significativa. Não cheguei a analisar a implementação interna de MINUS, mas o tempo de execussão aumenta consideravelmente.

**Comment by fredsonaguiar** [comment]
A query foi corrigida usando a lib, mas mantenho FILTER,  pela perfórmanece apresentada.

**Comment by arademaker** [comment]
Não entendi o comentário sobre substituir uma query por três. Não sugeri isso. Mas sim modularizar o máximo as verificações. Uma coisa é garantir que tudo que tem lexicalForm é uma word e que toda word tem lexicalForm. Outra coisa é identificar as words que não são valor para nenhuma outra propriedade de outra uri.

sobre minus vs filter, faz sentido que cada query engine tenha lá sua performance melhor com uma ou outra construção.

**Comment by fredsonaguiar** [comment]
Havia entendido mal, desculpe. Adicionamos o tipo `Word` a tudo que possui `lexicalForm`. Por outro lado, tudo que é `Word`, e não possui `lexicalForm` é removido. Quando a ação acima é aplicada, essa propriedade vale, e podemos usar a versão simplificada da query como sugeriu.

https://github.com/FredsoNerd/py-ownpt/blob/f2434bea02622c917e8e5a26bccde23b6820b7a9/pyownpt/repair.py#L144
https://github.com/FredsoNerd/py-ownpt/blob/f2434bea02622c917e8e5a26bccde23b6820b7a9/pyownpt/repair.py#L228
