### ISSUE TITLE
código precisa de revisão

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#4]
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L78-L79

Novamente aqui temos um problema. A query usando corretamente a lib seria como abaixo e passando os namespaces:

```sparql
SELECT ?s WHERE {
  { ?s wn30:word ?w . } 
  UNION 
  { ?s a wn30:WordSense . } 
  FILTER NOT EXISTS { ?ss wn30:containsWordSense ?s . }
}
```

Mas vc está fazendo duas coisas de uma vez. Melhor separar as verificações. Primeiro queremos saber se todo ?x que tem a propriedade wn30:word é tipado corretamente como wn30:WordSense:

```sparql
SELECT ?s 
WHERE {
  { ?s wn30:word ?w . } 
  minus
  { ?s a wn30:WordSense . } 
}
```

Temos 39 casos! E também temos 39 casos inversos, coisas que são `WordSense` e não tem wn30:word:

```sparql
SELECT ?s 
WHERE {
  { ?s a wn30:WordSense . } 
  minus
  { ?s wn30:word ?w . } 
}
```

Note que envolver o predicado `wn30:containsWordSense` aqui é missleading. Se perguntarmos se tudo que é sense de algum synset tem o tipo wn30:WordSense, a query abaixo, a reposta é sim, pois nada é retornado:

```sparql
SELECT ?s 
WHERE {
   ?ss wn30:containsWordSense ?s .
  minus
  { ?s a wn30:WordSense .  } 
}
```

E o inverso também não retorna nada, logo todo ?x que é WordSense tem algum synset que containsWordSense ?x:

```sparql
SELECT ?s 
WHERE {
  ?s a wn30:WordSense .
  minus
  { ?ss wn30:containsWordSense ?s .  } 
}
```

Logo sua query acima não estava retornando WordSense desconectados, mas `WordSenses` sem `wn30:word` ou coisas com `wn30:word` sem o tipo `WordSense`. Curiosamente 39 casos ambos. Uma 39 casos de blank nodes, outra 39 casos de uris wordenses-XXXXXX-P-X ... logo me parece ter sido algum erro de processamento.

**Comment by fredsonaguiar** [comment]
Na verdade, não estamos retornando `WordSenses sem wn30:word`. Diante da análise que apresentou, todo WordSense é objeto de um Synset, logo estaríamos retornando apenas `Coisas que possuem wn30:word` e que não são objeto de um Synset. Esses casos são precisamente os 39 BlankNodes que não foram substuidos. Esses são de fato Senses mal tipados, e deveriam ser removidos por essa ação.

Ao mesmo tempo, embora não ocorra no arquivo original, a proposta da ação é remover os Senses deconexos, logo faz sentido manter a busca pelos Senses também por tipo.

Qualquer dúvida, basta reabrir a discussão.
