### ISSUE TITLE
uso correto de prepared query

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#5]
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L91-L92

**Comment by arademaker** [comment]
```sparql
SELECT ?s1 ?s2 
WHERE {
  ?ss wn30:containsWordSense ?s1 ;
      wn30:containsWordSense ?s2 . 

  ?s1 rdfs:label ?l . 
  ?s2 rdfs:label ?l .
  FILTER ( STR(?s1) < STR(?s2) )
}
```

**Comment by arademaker** [comment]
Uma consulta complementar seria se dois senses diferentes não acabam apontando para words com mesmo lexical form. Note que não precisa do STR para comparar URIs:

```sparql 
SELECT ?s1 ?s2 
WHERE {
  ?ss wn30:containsWordSense ?s1 ;
      wn30:containsWordSense ?s2 . 

  ?s1 wn30:word/wn30:lexicalForm ?lf . 
  ?s2 wn30:word/wn30:lexicalForm ?lf .
  filter ( ?s1 < ?s2 )
}
```

**Comment by fredsonaguiar** [comment]
Obrigado pela sugestão da query. Corrigido. Sobre a consulta complementar, antes dessa rotina, garantimos que todo Sense possua label, e que os labels dos Senses para corresponder as Words, logo seria equivalente.

https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L28
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L31
