### ISSUE TITLE
uso correto da lib

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#6]
https://github.com/FredsoNerd/py-ownpt/blob/ea1767df6747dd0ff49d371dd6a8868a0ae8fcca/pyownpt/repair.py#L104

```sparql
SELECT ?w1 ?w2 
WHERE { 
  ?w1 wn30:lexicalForm ?l . 
  ?w2 wn30:lexicalForm ?l . 
  FILTER ( ?w1 < ?w2 )
}
```

No RDF do repositório só retorna um caso.

**Comment by fredsonaguiar** [comment]
Aqui um fato: notei resultados diferentes quando usamos `?w1 < ?w2` e `STR(?w1) < STR(?w2)`. Aparentemente, a comparação entre RDF Terms deveria ocorrer apenas como igualdade ou difrença, não maior ou menor. Veja [OperatorMapping](https://www.w3.org/TR/sparql11-query/#OperatorMapping). É possível que a comparação direta seja por uma especificação mais recente, ou específica da triple store em que está testando.

De todo modo alterei a query utilizando a API, mas introduzindo STR.

**Comment by arademaker** [comment]
ok, o uso de STR tá justificado então.
