### ISSUE TITLE
Words with/without underscore 

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#7]
http://wn.mybluemix.net/synset?id=01184814-n

Neste synset temos uma expressão onde espaço está marcado com underscore e uma sugestão com espaços. Idealmente, no final do processo, não queremos palavras que sejam iguais módulo underscore.

Words com underscore devem ser substituídas por words com espaço.

**Comment by arademaker** [comment]
este problema foi resolvido? Please reportar status aqui @FredsoNerd

**Comment by fredsonaguiar** [comment]
Yes. One of our repairing actions, present after updating, in the `repair_words`, responsible for, among other actions, `format_lexicals`, i.e. remove duplicated spaces, underscores, etc.

https://github.com/own-pt/py-ownpt/blob/607c60cdacdd47b482ebf10856c80e5bafdc16be/pyownpt/repair.py#L67-L85

It is normally called after updating actions, in `pyownpt.cli.update`:

https://github.com/own-pt/py-ownpt/blob/607c60cdacdd47b482ebf10856c80e5bafdc16be/pyownpt/cli/update.py#L88-L91
